### PR TITLE
NFT-374 feat: Show LTV and USD conversion on loan page

### PR DESCRIPTION
**Pull request by cnasc**
image

image

### CODE REVIEW

**Comment by jringenberg** [comment]
On the Collateral details, the extra value starts running into the stuff below it.
Here's a tweak: `line-height: 28px` and `padding-bottom: 5px` on the stack
image

We should use the same spacing (line-height) on the conversion for Loan Amount in the header too - I think it's inheriting a 32px line-height so if we specify 28px in that stack it should match. 

It's also weird that "Loan Amount" is aligning to the _center_ of the stack now - what we really want is for "Loan Amount" to still align directly with (ex) "420.69 DAI" and have the USD conversion appended beneath that pair. Here's what we want, faked with margins (I'm not sure how this could be done in a semantically correct way)
image

**Comment by cnasc** [comment]
> It's also weird that "Loan Amount" is aligning to the center of the stack now
I've just pushed a change that makes the terms go to the top instead of being center-aligned but it doesn't look like a positive change to me

**Comment by jringenberg** [comment]
> I've just pushed a change that makes the terms go to the top instead of being center-aligned but it doesn't look like a positive change to me

Haha, agree! We want the labels to align to the text itself, not to the top of the (invisible) container they sit in. I think a quick fix that gets us to the right place is to add a 'line-height: 26px;' to the left column labels (to `dt`) so that our top-aligning boxes _both_ contain text elements set off from the edge, if that makes sense. Here's now that looks:
image

In that image I've also adjusted the spacing between rows, which is generous and letting this section grow a bit too tall now that we're adding to it. `row-gap: calc(var(--gap) / 3);` (instead of the current `/2`)

**Comment by cnasc** [comment]
@jringenberg latest published

**Review by adamgobes — APPROVED** [review]
:shipit:

**Pull request merged**
